### ISSUE TITLE
Achieving the same behavior in a fragment?

### ISSUE THREAD

**Issue by leicht-io** [miguelhincapie/CustomBottomSheetBehavior#1]
I have a navigation drawer with fragments where one of the fragments inflates a Google Maps fragment. 

Is it possible to achieve the same behaviour when using the same setup as i do?

**Comment by miguelhincapie** [comment]
Hi ChristianLJ,

Yes, its possible.
1. About the Map:
   
   If you see [activity_main.xml](https://github.com/miguelhincapie/CustomBottomSheetBehavior/blob/master/app/src/main/res/layout/activity_main.xml) you will find that I'm using a dummy FrameLayout and below it I have commented the real one that use a map.
   In other words you can use whatever you want :)
2. About Fragment:
   I used regular XML and official stuff so I'm almost sure there is no problem inflating it from a Fragment.

Note: my apologize if you found any grammar/spelling error.

**Comment by miguelhincapie** [comment]
@ChristianLJ can you tell me please if you got it or if you need help?

**Comment by leicht-io** [comment]
@miguelhincapie i did. Thank you.

**Comment by rakesh1988** [comment]
@ChristianLJ I am having difficulties in handling navigation drawer, fragment and bottomsheet.

Can you please give me pointers as to how you managed to solve the issue?

My setup is in the following way.
- blank activity(call it MainActivity) with a frame layout which gets loaded with a map fragment by default.
- toolbar that holds the navigtion drawer is in MainActivity. 
- in fragment i have the second toolbar that shows the X button when expanded.

Problem is the fragment's toolbar is not hiding the activity's toolbar.

My fragment looks like https://i.imgur.com/dSi3qE4.png

Any help is much appreciated.
