### ISSUE TITLE
Bad position for backdrop image when starting in STATE_ANCHOR_POINT state

### ISSUE THREAD

**Issue by miguelhincapie** [miguelhincapie/CustomBottomSheetBehavior#12]
Sup @akaN44,
I'm implementing our developer in another project and I found this issue:
Lets say I have 2 activities, A and B. In B I implemented the CustomBottomSheetBehavior, so if I start activity B from A setting the state (`setState(BottomSheetBehaviorGoogleMapsLike.STATE_ANCHOR_POINT)`) the backdrop image doesn't start in the correct position. It's starting like if it was in STATE_COLLAPSED state.

I will give a look at this soon or late because I need it for the app that I'm developing but if you can give me a hand with this I will appreciate it so much!

**Comment by akaN44** [comment]
Hi Miguel,

So if I understand, You have two activity A and B. The B activity have the BottomSheet and when you start activity B you are setting the state of the BottomSheet to state STATE_ANCHOR_POINT in the onCreate method of B ? 

The problem might be that the BackDropBehavior don't have a SavedState yet and the position of the BackDrop image is calculated at the behavior initialisation and probably don't take count of the state you are setting. 

I already improved all behaviors and their usage but I didn't push the updates yet. I'll try to reproduce your issue and push a fix over the weekend.

Let me know if I misunderstand your issue.

**Comment by miguelhincapie** [comment]
Yep you understood it well!.
Thx very much for your help.

**Comment by akaN44** [comment]
Hi Miguel,

Sorry for late reply, I was pretty busy. 
What you want to achieve is actually working with the current code in your repo.
Make sure you updated the BackDropBottomSheetBehavior especially the init method.

**Comment by caiquebertan** [comment]
Hello @akaN44 and @miguelhincapie!

Same thing is happening to me. I'm creating an activity with a recyclerview inside, and a bottomsheet with details about recyclerview's item.

If I only slide the bottomsheet, works like a charm. But I want that when the user clicks the item on recyclerview, the bottomsheet popups on anchor point state. 
I'm using a simple ImageView as BackDrop, the ImageView gets confused when I click on the recyclerview and doesn't show up in the right place until I touch somewhere on the screen. And when I slide back the ImageView doesn't make the parallax correct and stops in the middle..

Any ideas? I only call mBottomSheetBehavior.setState(BottomSheetBehaviorGoogleMapsLike.STATE_ANCHOR_POINT); 
on the click of the recyclerview.

And sorry if the english is bad...

Thanks!!

**Comment by akaN44** [comment]
I see the problem know. It's because you use a recyclerView (the backdrop behavior react to it). I'll fix that soon.
On Nov 16, 2016 12:44 PM, Caique Bertan <notifications@github.com> wrote:Hello @akaN44 and @miguelhincapie!

Same thing is happening to me. I'm creating an activity with a recyclerview inside, and a bottomsheet with details about recyclerview's item.

If I only slide the bottomsheet, works like a charm. But I want that when the user clicks the item on recyclerview, the bottomsheet popups on anchor point state. 
I'm using a simple ImageView as BackDrop, the ImageView gets confused when I click on the recyclerview and doesn't show up in the right place until I touch somewhere on the screen. And when I slide back the ImageView doesn't make the parallax correct and stops in the middle..

Any ideas? I only call mBottomSheetBehavior.setState(BottomSheetBehaviorGoogleMapsLike.STATE_ANCHOR_POINT); 
on the click of the recyclerview.

And sorry if the english is bad...

Thanks!!

**Comment by miguelhincapie** [comment]
Hey @caiquebertan something similar is happening with AppBarLayout. I'm working on a big app that use so much this component (bottom sheet). In some weeks I will be focused on fix it if @akaN44 has not done it already.

Don't apologize for your english bro! ;) at this time all ppl should know at least 2 languages. I can speak spanish if it's useful for you

**Comment by akaN44** [comment]
So to be more clear, the Backdrop behavior react to any NestedScrollView in the same coordinatorLayout . The BottomSheet is a  NestedScrollView but sadly other views can also be a NestedScrollView like the RecyclerView for example. It's not a big fix, I'll try to do it tonight.

**Comment by caiquebertan** [comment]
Hey, thanks for the quick response!

And thanks for the great work on that library.

Even that I understand the problem, I really don't know how to fix that
haha. So I'll be waiting for the next updates...

Thank you again!

---

Caique Bertan
Desenvolvedor Mobile / Java
+55 11 985433820
http://www.linkedin.com/profile/view?id=183054270

2016-11-16 23:37 GMT-02:00 Paul-Marie Tetedoie notifications@github.com:

**Comment by miguelhincapie** [comment]
OMFG! I was about to finish a big explanation about what I found and miss click on back button...Now I'm lazy to copy everything again... I'm gonna do my best.

**Comment by miguelhincapie** [comment]
Hi @caiquebertan 
I found 4 things that you should check in order to verify if you are using this component properly.

First I'm going to give a overview about the app that I'm finishing:
The app shows promotions related to user position. All information is downloaded from server using `JSON` and AndroidAnnotation.

1. If you take a look at `activity_main.xml` file in the sample you will notice we are using a <include> tag in line 60.
For an example, its fine to use that for the bottom sheet content but what I found out developing one big application is: you should change it for a `Fragment`.
I had some problems related to refresh the content of the bottom sheet when the user tapped an element in the map or if the app got opened in that view from a deep link (some times the backdrop didn't start in right position, some times the bottom sheet didn't start in expanded mode and some times didn't paint all visual components).
What I did was change that <include> for a <fragment> and then I fixed the refresh problems.

2. After that I found that some devices has problems drawing lot of components in bottomsheet component. I mean, in some real devices I was getting an error like this: `W/OpenGLRenderer: Layer exceeds max. dimensions supported by the GPU (720x4620, max=4096x4096)`. So I had to add:
 `if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP)
            coordinatorLayout.setTransitionGroup(true);` 
to the CoordinatorLayout in `activity_main.xml`.

With those 2 points I fixed the weird backdrop behavior, start bottom sheet behavior and refresh problem.

3. Now in `activity_main.xml`, in the `Toolbar` inside merged AppBarLayout, I accidentally changed `app:title="@string/key_binding_default_toolbar_name"` for `tools:title...`. Without this initial value I found Merged App bar doesn't work properly.

4. After fix point 3 I realized I was changing the content of the bottom sheet swapping fragments (the fragment that I created in point 1) and I was setting the title of point 3 BEFORE attach it to the activity.

Hope those 4 points help you @caiquebertan .

Now @akaN44 I didn't dig much in the `init` method in `MergedAppBarLayoutBehavior` but I guess we can change that "link system" for tag() or some custom tag. I mean, in that class we found the TextView looking for a child with text: "Modal-Toolbar-Title" in method `findTitleTextView()`, if you set another title in XML or in code before that method got called the AppBar didn't work well.
Let me know what do you think please.

**Comment by miguelhincapie** [comment]
@akaN44 Another thing that I noticed is if the content height of the Bottom sheet is less than device screen height you can see the map below your bottom sheet if you scroll it.
I tried resizing the bottom sheet Layout but doesn't work all time... after search a lot I found a work around using `getViewTreeObserver()` and `addOnGlobalLayoutListener`.

Something like this:

> ViewTreeObserver observer = principal_container.getViewTreeObserver();
        observer.addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override
            public void onGlobalLayout() {
                fixBottomSheetHeight();
                principal_container.getViewTreeObserver().removeOnGlobalLayoutListener(this);
            }
        });

**Comment by miguelhincapie** [comment]
ohhh I'm feeling like walking in circle... I'm still have the problems.

@akaN44 if in our sample project - MainActivity - onCreate you add this line of code `behavior.setState(BottomSheetBehaviorGoogleMapsLike.STATE_ANCHOR_POINT);` you will see one of the problems, look the AppBar in the screenshot 
![Uploading _device-2017-01-07-230338.png…]()_

**Comment by miguelhincapie** [comment]
Hi @caiquebertan I just committed a new version in where I fix some initial position of components (look at commit change log if you wanna know more).
