### ISSUE TITLE
Achieve as a seprate activity

### ISSUE THREAD

**Issue by am2222** [miguelhincapie/CustomBottomSheetBehavior#13]
Hi,
I noticed that If I want to use this view I have to use it in a new activity, Is there any way to run it on existing activity?I mean if we have an existing activity when our new activiry with Bottonsheet behaviour runs it covers other activity, even when it is collapesed. Here I want that this activiy runs and we can out back activity too.Is it possible?

**Comment by akaN44** [comment]
Hi, 
I'm not sure to understand what you want to achieve. Can you be more clear ?
Why do you want to start a new activity dedicated to the bottomsheet ? If you start a new activity, you'll no longer be able to interact with the current activity which will be stopped by Android. You can use the behaviors inside any existing activity.

**Comment by am2222** [comment]
Hi,
In fact I want to use this behavior like a notification when user goes to spasial location it shows itself and user use it..It seems such a thing is not any android's feature?isn't it?

**Comment by akaN44** [comment]
If you want to hide the bottomSheet at some point, you can do it. To do that just set the mode to hidden then when you want to show it set the mode to collapsed. 

Android will not allow you to run two activities at the same time, when you start an activity, the current activity will be stopped So you can no longer interact with it. For example, let say you have an activity in the backgroud a map or a list of items. If you want to use a separate activity dedicated for the bottomsheet, as soon as you will start this activity, the background activity will be stopped. So, you'll not be able to use the background activity even in collapsed mode, even if you can partially see the stopped activity behind the bottomsheet.
Please take a look at the Android Activity Lifecycle. https://developer.android.com/training/basics/activity-lifecycle/index.html

**Comment by am2222** [comment]
@akaN44  thanks for your detailed answer.
