### ISSUE TITLE
How can I hide ButtomSheet 

### ISSUE THREAD

**Issue by am2222** [miguelhincapie/CustomBottomSheetBehavior#14]
Hi,
How can I hide ButtomSheet in activity?I used this code

`behavior.setState(BottomSheetBehaviorGoogleMapsLike.STATE_HIDDEN);
`

But does not change it..thanks

**Comment by miguelhincapie** [comment]
Hi there, Im developing a big app that use this code. In those 2 next weeks I will be working in other things of the app. I hope I will take it back for dicember 8 more or less.

**Comment by am2222** [comment]
thanks very much, I hope every thing goes right with your application

**Comment by rakesh1988** [comment]
@am2222 were u able to hide the bottom sheet?

**Comment by am2222** [comment]
@rakesh1988 no I am waiting for some results

**Comment by rakesh1988** [comment]
actually i was able to do ````behavior.setHideable(true);```` which will enable the hiding feature...
but the FAB should be handled manually.

**Comment by rakesh1988** [comment]
have you tried using the whole setup in a activity, navigation drawer and fragment setup??

**Comment by rakesh1988** [comment]
I am getting a ````java.lang.RuntimeException: Could not inflate Behavior subclass ```` error

**Comment by miguelhincapie** [comment]
Hey @am2222  and @rakesh1988 sorry for not answering before. This week I have resumed work in this project, take it easy and I will help you asap.

**Comment by miguelhincapie** [comment]
Like @rakesh1988  said, you can use `setHideable()` in code or you can use `app:behavior_hideable="true"` in XML.

I will add some behavior for what you said about FAB, I mean, it should be hidden too.

**Comment by am2222** [comment]
@miguelhincapie, @rakesh1988 can you please share an example how to hide it?

**Comment by rakesh1988** [comment]
when u are initialising the behavior u need to just set `behavior.setHideable(true);`

**Comment by am2222** [comment]
@rakesh1988  thanks very much

**Comment by miguelhincapie** [comment]
By the way there is a little bug related to backdrop beginning position. I will fix it today.

**Comment by miguelhincapie** [comment]
I just commit a new version.
FAB get hidden automatically when bottomSheet is on collapsed state or going to this state.
