### ISSUE TITLE
Wrong positioning of backdrop image when relaunching slider from STATE HIDDEN

### ISSUE THREAD

**Issue by traabefi** [miguelhincapie/CustomBottomSheetBehavior#16]
Hi, nice project, but I have one problem. When I hide the bottom sheet, and then relaunch it, the image does not react properly as it should. could you plese do something about that ?

**Comment by miguelhincapie** [comment]
Hi @traabefi I have been working in this project again and I have 2 question about what you found:
1. have you change `app:behavior_peekHeight` and `app:anchorPoint`.
2. can you give me more details of how do you hide it and then relaunch it? (buttons, using scroll listeners, etc)

if you can share a sample or snipet code in where we can reproduce the error should be good! :D

**Comment by miguelhincapie** [comment]
Download new code and tell me if it got fixed please.

**Comment by traabefi** [comment]
Yes that fixed that issue
