### ISSUE TITLE
Scrolling down view pager is scrolling the bottomsheet as well, how ?

### ISSUE THREAD

**Issue by gmeral** [miguelhincapie/CustomBottomSheetBehavior#18]
@miguelhincapie  How is it that when scrolling down the sliding view pager, the bottomsheet scrolls aswell ?
I'm working on a project that is using a very similar bottomsheet and in my case, scrolling the backdrop view down is not affecting my bottom sheet.
I do not understand how it works in your case, could you explain it ? Is the "scrollable part" of the bottom sheet extended or something like this ?

Thank you for your answer.

**Comment by miguelhincapie** [comment]
Hi @gmeral, that question can be answered by @akaN44, he improved that part of the project.
Like I said in others threads before, I will be working hard in this project asap, after finishing some functional requirements of an app.

**Comment by gmeral** [comment]
Okay thank you, let's hope he is going to be passing by sometime soon then :)

**Comment by akaN44** [comment]
@gmeral Take a look at this commit https://github.com/miguelhincapie/CustomBottomSheetBehavior/commit/b66ef1771e9e63048f57a8f7c41bef083c902da4

**Comment by gmeral** [comment]
Oh i see, it's very clear now, then you added an if to only have this behaviour in STATE_ANCHOR_POINT.
Thanks a lot, i integrated these changes and it works like a charm.

**Comment by ChristopheVersieux** [comment]
I am also curious, as the ViewPager disable the horizontal scroll for the Map behind, which looks like a dirty hack.
As soon as we replace the ViewPager with an ImageView, the map can now move...
Commit referenced by @akaN44 is now overwritten ...

**Comment by gmeral** [comment]
In BottomSheetBehaviorGoogleMapsLike.java : 
In the onInterceptTouchEvent method you have to replace this piece of code : 
```
View scroll = mNestedScrollingChildRef.get();
if (scroll != null && parent.isPointInChildBounds(scroll, initialX, mInitialY)) {
    mActivePointerId = event.getPointerId(event.getActionIndex());
    mTouchingScrollingChild = true;
}
```

by 

```
if(mState == STATE_ANCHOR_POINT){
            mActivePointerId = event.getPointerId(event.getActionIndex());
            mTouchingScrollingChild = true;
        }else {
            View scroll = mNestedScrollingChildRef.get();
            if (scroll != null && parent.isPointInChildBounds(scroll, initialX, mInitialY)) {
                mActivePointerId = event.getPointerId(event.getActionIndex());
                mTouchingScrollingChild = true;
            }
        }
```
