### ISSUE TITLE
How to click button in mainActivity to expanded BottomSheet

### ISSUE THREAD

**Issue by helmifluida** [miguelhincapie/CustomBottomSheetBehavior#2]

**Comment by miguelhincapie** [comment]
Hello there,

You can do it following next steps:
1. Move the objet: `BottomSheetBehaviorGoogleMapsLike behavior` variable from `onCreate` on mainActivity to be a member class variable.
2. Create a clickable element in mainActivity XML (like a `Button`), set `setOnClickListener` method with this line of code: `behavior.setState(BottomSheetBehaviorGoogleMapsLike.STATE_EXPANDED);`

That's all. Tell me please if you get it or if you need more help.

**Comment by miguelhincapie** [comment]
Seem like you got it, so I will close this.
