### ISSUE TITLE
BottomSheet collapse bug

### ISSUE THREAD

**Issue by vit001** [miguelhincapie/CustomBottomSheetBehavior#24]
Hi - great lib!! 
I ran into the following bug:
1) Fully expand the bottom sheet
2) Scroll the bottom sheet up
3) Collapse the bottom sheet using the X toolbar icon 
Bug: the Bottom sheet doesn't scroll to the top. Please see video: https://vimeo.com/200454784

**Comment by miguelhincapie** [comment]
Hi @vit001,

Can you explain me a little bit what do you expect to happen when you press X in toolbar?
I can't see the bug xD. Because following the Google Maps app, if you press same icon (they have an arrow), the bottomsheet is collapsed like you show in the video.

**Comment by vit001** [comment]
Hi @miguelhincapie  - thanks for the reply. If you look at the last frame in the video, you see that the collapsed BottomSheet is white and says 'Text dummy 1'. I expect it to be blue and say 'Title dummy', just like when you first start the demo.

**Comment by miguelhincapie** [comment]
oh I got it! but I wait. The text is just about different text in XML or code.
But the scroll behavior is 100% bug. I can't spend time in this project for next 2 weeks, so after that I will see what is going on and commit asap... or if you want to do it... :D I will be so happy.

**Comment by vit001** [comment]
Here is a better demonstation of the bug: https://vimeo.com/200522363

I will take a look to see if I can fix it.

**Comment by deiauk** [comment]
Actually you can use this method bottomSheet.scrollTo(0, 0); when bottomSheet is in STATE_COLLAPSED
