### ISSUE TITLE
How to prevent BottomSheet from swiping down completely?

### ISSUE THREAD

**Issue by vit001** [miguelhincapie/CustomBottomSheetBehavior#25]
How can I prevent the BottomSheet from being completely swiped down off the screen? The video shows the end-state I would like to prevent (no BottomSheet visible):
https://vimeo.com/200455034

**Comment by miguelhincapie** [comment]
Hi there,

just delete `app:behavior_hideable="true"` in NestedScrollView that is using `BottomSheetBehaviorGoogleMapsLike` behavior.

**Comment by vit001** [comment]
Thank you! That was easy ... :)
