### ISSUE TITLE
Fix for bottom sheet fling/snap/settle bugs

### ISSUE THREAD

**Issue by vit001** [miguelhincapie/CustomBottomSheetBehavior#26]
There are several bugs related to snapping back to the anchor state:

1) In Google Maps the anchor state is sticky - the Backdrop Element needs to be pulled down at least 50% before the Bottom Sheet collapses. If it is pulled less than 50% the Bottom Sheet snaps back to the anchor. The behavior of the lib is different - as soon as the Backdrop Element is pulled down even a tiny amount and released, the Bottom Sheet collapses rather than snapping back. Please see video:
https://vimeo.com/200534893

2) Similarly to 1), going from anchor state to expanded should require making the Backdrop half-way shut. Currently dragging up from anchor state by an infinitesimal amount and the lifting the finger is enough to expand the Bottom Sheet. Please see video:
https://vimeo.com/200536226

3) Current lib behavior does not take fling velocity into account.

4) Current lib behavior does not force stop at anchor state.

Pull request for all fixes here. Please let me know if you come across any bug with this.
https://github.com/miguelhincapie/CustomBottomSheetBehavior/pull/27

**Comment by miguelhincapie** [comment]
I guess we are missing something in what he did in one of those commit related to fling.
Someone from my last company show me the app behavior in one smartphone with an old version of this library and the new one (he download my app from the market and that one has the last commit). In old one I tried like 12341234 times reproduce the issue related to "jump" anchor_point and get from collapsed to expanded in one shoot but I couldn't. Meanwhile in the news one was easy to reproduce it.
So I guess we are missing a little logic behind those changes.

**Comment by vit001** [comment]
Sorry - I am not clear on what the issue is. Are you saying the 'stop at anchor' worked BEFORE PR#27 and doesn't work AFTER PR#27?

**Comment by miguelhincapie** [comment]
In somehow yes, I mean, like I said, I tried so many times in an old version of the lib and I couldn't reproduce "jump state" behavior (It could be I didn't try in the right way... no idea). But what I'm sure is that was easy to reproduce it using last version of the lib, so I'm guessing we are missing some logic in the new fling behavior.

**Comment by vit001** [comment]
Can you take a look at my fork and see if everything works? I've made many changes over the past few days. If it works I can issue a PR.

https://github.com/vit001/CustomBottomSheetBehavior

**Comment by vit001** [comment]
My phone died unfortunatelly so I am stuck with the emulator for a couple of days , very clunky... :(

**Comment by vit001** [comment]
OK, I see the issue - I have my BottomSheet in a Horizontal ViewPager (another layer of NestedScrollingParent), so some of the code doesn't work the same in your lib demo. I am going to push out my Horizontal ViewPager code as a lib so you can take a look, and maybe you'll find use for the paging ability as well ... :)

**Comment by miguelhincapie** [comment]
yeah, because all the different configurations you can have with this lib, I'm going to make 2 or 3 demos plus the principal one. It sounds good having integration with that lib you are going to release.

note: I don't like how it sounds when you say "in your lib" :D. I mean, I just started this lib but it has grown because @akaN44 and you... so it's better if you say "our lib".

**Comment by vit001** [comment]
@miguelhincapie - Still working on a clean demo and fixing toolbar, but you can check out https://github.com/vit001/CustomBottomSheetBehavior - the paging and scrolling works perfrect for me.

https://vimeo.com/203024083

By the way, if you don't want the horizontal pager functionality, you can always provide an adapter with only one item.
