### ISSUE TITLE
When user touches screen during fling the state transitions to end state than scrolls back a little

### ISSUE THREAD

**Issue by vit001** [miguelhincapie/CustomBottomSheetBehavior#30]
Google Maps behavior is such that a touch after a fling (while fling is in progress) is ignored. Current lib behavior is such that when user touches screen during fling, the state transitions to the end state, then scrolls back a little towards the touch. 

I will try looking into this issue, but help is appreciated as well.

**Comment by miguelhincapie** [comment]
it's what you were talking in #15 right?

**Comment by vit001** [comment]
No this is a different issue. I'll post a video.
