### ISSUE TITLE
Bottom Sheet should have touchSlop

### ISSUE THREAD

**Issue by vit001** [miguelhincapie/CustomBottomSheetBehavior#31]
To mimic Google Maps behavior, the Bottom Sheet should have touch slop as provided by ViewConfiguration.getTouchSlop(). Currently, there is zero touchSlop which makes the scroll behavior too sensitive and jittery.

I am stumped by this one - anyone have ideas?

**Comment by miguelhincapie** [comment]
At night I will take a look.
@akaN44 can you give us a hand (if you have time of course)

**Comment by vit001** [comment]
I have a solution for touch slop that works, but it requires replacing NestedScrollView with a custom NestedScrollingParent (SloppyNestedScrollView). As a result, it is tied to a specific version of Design Support Lib, and as new versions of Design Support Lib come out, it will be necessary to update SloppyNestedScrollView to stay in sync, Let me know if you are interested in going this route.
