### ISSUE TITLE
Give shadow to top edge of collapsed bottom sheet 

### ISSUE THREAD

**Issue by vit001** [miguelhincapie/CustomBottomSheetBehavior#32]
The Google Maps app has a shadow above the bottom sheet when it is in collapsed state. Any ideas on how to implement it? I tried the obvious - setting elevation in xml, but without success (shadow is only cast downwards below the bottom sheet, not above). Also no success with ShadowLayout (it cannot paint over the main content behind the bottom sheet.

**Comment by miguelhincapie** [comment]
What about this:

```
<View
            android:id="@+id/oferta_shadow"
            android:layout_width="match_parent"
            android:layout_height="@dimen/ofert_shadow_height"
            android:background="@drawable/shadow"/>
```

```
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">

    <gradient
        android:startColor="#997e7e7e"
        android:endColor="#0000"
        android:type="linear"
        android:angle="90"> <!-- Change this value to have the correct shadow angle, must be multiple from 45 -->
    </gradient>

</shape>
```

using that view upper inside the bottomsheet content

**Comment by vit001** [comment]
Good thinking! The problem I ran into is that the viewpager with parallax photos shows underneath the shadow when the bottomsheet is collapsed, and setting a margin on the viewpager seems to get ignored ...

**Comment by vit001** [comment]
OK, I have a solution. Had to modify the backdrop behavior to adjust for the shadows. Will post a PR.

**Comment by deividas717** [comment]
You can also do this



      <android.support.design.widget.CoordinatorLayout
          android:id="@+id/coordinatorlayout"
          android:layout_width="match_parent"
          android:layout_height="match_parent">

        <View
            android:id="@+id/bottom_sheet_shadow"
            app:layout_anchor="@+id/bottom_sheet"
            android:layout_width="match_parent"
            android:layout_height="24dp"
            android:background="@drawable/bottom_sheet_shadow" />

        <android.support.v4.widget.NestedScrollView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical"
            app:behavior_peekHeight="@dimen/bottom_sheet_peek_height"
            android:id="@+id/bottom_sheet"
            app:layout_behavior="com.BottomSheetBehaviorGoogleMapsLike"
            app:anchorPoint="@dimen/anchor_point"
            app:behavior_hideable="true"
            android:fitsSystemWindows="true">

            <include
                android:id="@+id/content"
                layout="@layout/bottom_sheet_content"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />

        </android.support.v4.widget.NestedScrollView>

    </android.support.design.widget.CoordinatorLayout>

**Comment by vit001** [comment]
That works! Much easier than what I had in mind! (Which involved adding the shadow to the scrollview and then having to offset the backdrop).

**Comment by miguelhincapie** [comment]
yeah @deiauk that is what I was talking about :D
by the way I'm feeling a little bad cuz I can't help you guys much on those days xD. I'm in the release of a big app that use this lib (https://play.google.com/store/apps/details?id=co.com.spyspot)

**Comment by vit001** [comment]
Looks like a nice app! It seems it's not available in my country but the screenshots look cool!

**Comment by miguelhincapie** [comment]
I'm closing the ready issues. Did you commit this one?

**Comment by vit001** [comment]
No, did not commit - do you want me to? By the way, adding a shadow requires a making a change to MergedAppBar partialBackgroundHeight to factor in the shadow height.

**Comment by miguelhincapie** [comment]
But what about if I don't wanna use shadow? do you have thought in a easy way to turn on/off this new effect?. I'm asking it because if you review the issues, there is one related to ignore one step. After that question I though... damn, I would developed it giving the option to choose what points I want to use, I mean (hidden, followed by collpsed, followed by anchor and then expanded... or just ignore one of them and jump to the next one).
