### ISSUE TITLE
BackdropBottomSheetBehavior.onDependentViewChanged return value bug

### ISSUE THREAD

**Issue by vit001** [miguelhincapie/CustomBottomSheetBehavior#33]
I have seen a rare bug where the Backdrop freezes and doesn't scroll along with the bottom sheet. I believe the bug has to do with the return value of the BackdropBottomSheetBehavior.onDependentViewChanged.
Per docs: "If the Behavior changes the child view's size or position, it should return true. The default implementation returns false." 
The implementation in this lib returns true if the size or position DO NOT change, and false with the DO change.

**Comment by miguelhincapie** [comment]
I though I had fixed it xD hahaha. It's a easy one.

**Comment by miguelhincapie** [comment]
ohh but the freezes behavior I think is more related to the issue that you reported some weeks ago in where all the content of bottom sheet some times doesn't get painted at all until a forced relayout happens... but I'm guessing xD
