### ISSUE TITLE
Allow dragging BottomSheet by grabbing Backdrop

### ISSUE THREAD

**Issue by vit001** [miguelhincapie/CustomBottomSheetBehavior#34]
Google Maps allows you to scroll the BottomSheet vertically by grabbing and dragging the Backdrop. Lib is missing this functionality. What do you figure is the best way to implement this?

**Comment by miguelhincapie** [comment]
hum? I'm a little confused, is that functionality not implemented yet? or is a different one? I mean, I just tried with the app in the market that I published last week and I can drag up or down the BottomSheet grabbing the Backdrop.

**Comment by vit001** [comment]
It's not working for me using the lib demo app...

**Comment by vit001** [comment]
Sorry I take it back! It's working - there is a problem on my end!
