### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by barbeau** [miguelhincapie/CustomBottomSheetBehavior#4]
This project is a great example!

Could you please add an open-source license to the project?

I'd prefer Apache 2.0 if possible.  Thanks!

**Comment by miguelhincapie** [comment]
Though I was used same as google apis, anyway its open-source but I will add it in README :D

**Comment by miguelhincapie** [comment]
Ready, I just copy paste Apache license from google's code.
Like I change in README, just give me vote up in stackoverflow: [question and answer about it](http://stackoverflow.com/q/37335366/1332549)

**Comment by barbeau** [comment]
Thanks!  I upvoted :).  Looks like you added the license in https://github.com/miguelhincapie/CustomBottomSheetBehavior/commit/dfbfb8624741e48fb182277cc4b5e94cf7c1f556, so I'll close this issue.

Thanks again!
