### ISSUE TITLE
In Android API 24 (7.0), BackdropBottomSheetBehavior fail

### ISSUE THREAD

**Issue by glauberrs** [miguelhincapie/CustomBottomSheetBehavior#48]
Hi,
In Android API 24 (Android 7.0), BackdropBottomSheetBehavior fail.
Just drag some times the AppBar.
Sample:

<img width="308" alt="motog4" src="https://user-images.githubusercontent.com/12559183/26883132-a83da05a-4b72-11e7-88e1-b8426494d2aa.png">

Regards,

**Comment by ghost** [comment]
+1

**Comment by miguelhincapie** [comment]
Hi, thank you for report this issue, at the moment I'm busy with an personal project. If you or someone can give me a hand fixing it, I would appreciate it :D

**Comment by ghost** [comment]
In BottomSheetBehaviorGoogleMapsLike I added one if statement but I don't like this solution, because when you manually drag the behavior it will block at some point like previously, at least this way when the view is expanded the UI will be refreshed.

```ruby
private void setStateInternal(@State int state) {
        if (mState == state) {
            return;
        }
        mState = state;
        View bottomSheet = mViewRef.get();
        if (bottomSheet != null && mCallback != null) {
            notifyStateChangedToListeners(bottomSheet, state);
        }
        Log.i(TAG, "setStateInternal: " + state);
        if(state == STATE_ANCHOR_POINT && bottomSheet!= null){
            bottomSheet.requestLayout();
        }
}
```

**Comment by vit001** [comment]
There is a framework bug where something gets garbage collected and dependents (like Backdrop) stop being notified. You do not want to call `requestLayout()` - that's very expensive and will lead to poor performance. Instead, in `BottomSheetBehaviorGoogleMapsLike`, add the following to `onNestedPreScroll`:
```
if ( mNestedScrollingChildRef.get() != null ) {
    CoordinatorLayout cl = (CoordinatorLayout)mNestedScrollingChildRef.get().getParent();
    cl.dispatchDependentViewsChanged( mNestedScrollingChildRef.get() );
}
```
This will make sure all dependents will be notified. Also, add the same to `SettleRunnable.run()`.

**Comment by glauberrs** [comment]
Thank you soo much vit001, Work like a clock!!

**Comment by ghost** [comment]
Thx! Working for me as well!
