### ISSUE TITLE
Content does not display correctly after changing the text

### ISSUE THREAD

**Issue by gp01kkky** [miguelhincapie/CustomBottomSheetBehavior#5]
Hi, Thank for sharing this

I have a problem changing the default text. After changing the text, it appears that it does not display it correctly with wrap_content not updating to the correct size and the default cheese image does not appear. Do you have any idea?

**Comment by miguelhincapie** [comment]
Hi,
Explain me a little bit about wich text are u trying to change please.

**Comment by gp01kkky** [comment]
Hi, I figured out that it is the wrap_content that uses previous size which was not updated after the length of text has changed in the bottom_sheet_content.xml layout. Managed to solve it by using the code here https://github.com/ea167/android-layout-wrap-content-updater.

But another problem is the cheese image does not appear when dragged up. I need to touch the top bar to make it appears. In my implementation, I have set the whole bottomsheet to setState(BottomSheetBehaviorGoogleMapsLike.STATE_HIDDEN) to hide it from the user when it wasnt in use. but when i set it to not STATE_COLLAPSE again after update of the text in the layout content the image dissapear. Also I have a touch listener for my map in the background, whenever i touch the image it registers a touch on the map, the image is not preventing touch from what's underneath it

**Comment by miguelhincapie** [comment]
Give me a few days and I will check it, I have a lot of work this week :S

**Comment by gp01kkky** [comment]
Hi, sure thanks a lot.

Hope you are able to replicate the problem. I think the problem still lies on 1) the content is not invalidated when I change the image source. 2) Cannot drag the bottomsheet down when touch on the image area because touch is registered in the layout underneath. If possible can you show how I can modify it to show multiple images with the slide just like in google map.

**Comment by akaN44** [comment]
I'll take a look as well as soon as I have spare time. For the ImageView not draggable in fact it has never been at this moment it's one of the major issue. I'll work on it. If you want to have multiple image like Google maps, You can use a ViewPager and put the behavior of the ImageView on it. Then put ImageViews in the Pager. I'll add it in the future. But I prefer to work on the issues first. Btw, the layout is not working well on pre-Lollipop devices. I have to work on that as well.

**Comment by akaN44** [comment]
I found a way to handle the scrolling of the ImageView. Basically, I allow the content outside of the NestedScrollView bounds (on the imageView in our case) to scroll. So the touch events on the ImageView are considered inside of the BottomSheet bounds which will make the bottomSheet scroll and the imageView scolling accordingly.  I'll try it with a ViewPager to see if the horizontal scrolling works.

**Comment by gp01kkky** [comment]
Hi, I understand what you said, but didnt manage to get it working. Would u mind to share how you did it? I tried making the outside scrollable, but behavior became weird. The image blocked the layout below it.

**Comment by akaN44** [comment]
Did you updated your code with the new behaviors ? What is your problem exactly now ?  What do you mean by make the outside scrollable  ? There is still some issues right now but it's almost working. We must improve animations and figure out a way to use a peak height greater than the toolbar height, to be close to the Google maps behavior. But actually, it's definitely not the way Google developed it. We only tried to mimic the behaviors.

**Comment by gp01kkky** [comment]
Hi, sorry if I misunderstood what you said, you mention about making the imageView to scroll. Do you mean making it scrollable? I still cant get the touch events on the imageview to be considered in the bottomsheet bound

**Comment by akaN44** [comment]
The scroll on the imageView is working. Just update the BottomSheetBehaviorGoogleMapsLike in your code.

**Comment by gp01kkky** [comment]
Oh right great, it is working!! sorry didn't notice the change.
