### ISSUE TITLE
Sliding down from STATE_COLLAPSED does not hide the bottomsheet

### ISSUE THREAD

**Issue by rjnsalvador** [miguelhincapie/CustomBottomSheetBehavior#50]
Hi, I would like to know how I can fix this problem.
If my bottomsheet is currently STATE_COLLAPSED, scrolling down does NOT hide it. 
If my bottomsheet is currently STATE_ANCHOR_POINT, scrolling down ON THE VIEWPAGER will hide it.

I cloned this sample project and it seems that is has the same issue, even if the bottomsheet is hideable (app:behavior_hideable="true"), on scrolling down by TOUCHING THE VIEWPAGER will hide the bottomsheet.

**Comment by miguelhincapie** [comment]
Did you get a solution for this? (taking back this project so I'm going to start fixing little things then the big ones)

**Comment by Tweener** [comment]
I can confirm this is still happening. 
This is the order of states when sliding down to try to hide it:
- STATE_COLLAPSED
- STATE_DRAGGING
- STATE_SETTLING
- STATE_COLLAPSED

Any news about that behavior?

**Comment by miguelhincapie** [comment]
No, but I'm going to put it in the list of my to-do :D... or if you wanna do it, go ahead

**Comment by Tweener** [comment]
I guess I'm like everyone else, I don't have time! 😆 If I can manage to find time, I'll do a PR, but you should not count on me.
