### ISSUE TITLE
How to prevent STATE_COLLAPSED and STATE_HIDDEN?

### ISSUE THREAD

**Issue by manufunk** [miguelhincapie/CustomBottomSheetBehavior#56]
Hi, I want to only have STATE_ANCHOR_POINT and STATE_EXPANDED. Means the STATE_ANCHOR_POINT is my default state and I want users to only scroll up to STATE_EXPANDED and back again to STATE_ANCHOR_POINT.

Is there any way to achieve this?

**Comment by miguelhincapie** [comment]
Oh sorry for being late on this post, did you find the way to achieve it?

**Comment by manufunk** [comment]
No worries I just closed it because it is a duplicate of my own thread :) I will try to implement this in a fork and after that ask you for merging it. However, it might take some time..

**Comment by miguelhincapie** [comment]
oh nice! ty for that
