### ISSUE TITLE
SecondAppBarLayoutBehavior improvement

### ISSUE THREAD

**Issue by akaN44** [miguelhincapie/CustomBottomSheetBehavior#7]
I re-developed the SecondAppBarLayoutBehavior to mimic the exact Google behavior. I'll clean the code and push it as soon as possible. Here is a preview.
![2016_07_27_17_49_54_17_51_11](https://cloud.githubusercontent.com/assets/4276053/17197658/9ab5c206-5423-11e6-912a-6e8ff88f8003.gif)

**Comment by miguelhincapie** [comment]
wow nice! let me know if you need something :D, but like I said in a previous post I a little bussy this week.
